[package]
name = "frostbite"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0"
walkdir = "2.4"
arboard = "3.2"   # cross-platform clipboard