[package]
name = "permafrost"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "permafrost"
path = "src/main.rs"

[dependencies]
dirs = "6.0.0"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0"
walkdir = "2.4"
arboard = "3.2"   # cross-platform clipboard