remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Frosts
description: pandas-inspired Excel scripting for Office Scripts

#Table of Contents Autoconfig
kramdown:
  toc_levels: 1..3
  auto_ids: true
  parse_block_html: true
  author: Joey Russoniello

#SEO Terms
url: "https://joeyrussoniello.github.io/frosts"
twitter_username: joeyrussoniello
github_username:  JoeyRussoniello