#Include the _includes directory for recycled HTML elements
include:
  - _includes

# Use Just the Docs theme (much more structured than Midnight)
remote_theme: just-the-docs/just-the-docs

title: Frosts
description: pandas-inspired Excel scripting for Office Scripts

# Automatically generate a table of contents on each page
just_the_docs:
  logo: "/images/frosts_logo.svg" # optional if you have a logo
  aux_links_new_tab: true  # optional, opens links in new tab
  nav_external_links:  # Enable aux_links in the navbar
    "View Frosts on GitHub": 
      - "//github.com/JoeyRussoniello/frosts"
  show_downloads: true
  search_enabled: true
  footer_content: ""
  footer_custom: true #Enable the custom footer HTML
  enable_copy_code_button: true

# Optional: Clean URLs
permalink: pretty

# SEO
url: "https://joeyrussoniello.github.io/frosts"
github_username: JoeyRussoniello

# Plugins required for GitHub Pages + Just the Docs
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed